server:
  port: 9001


#NEED to add node1 and node2 hostname into /etc/hosts/
#define one node and register it in node2
eureka:
  instance:
    appname: node2
    prefer-ip-address: true
#    hostname: node2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false