server:
  port: 9051

logging:
#  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
#  level.org.springframework.cloud.sleuth.log: DEBUG
#  level.org.springframework.cloud.sleuth.trace: DEBUG
#  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG

spring:
  zipkin:
    # the url cannot append with zipkin keyword since the latest version is V2
    # https://github.com/openzipkin/zipkin/issues/1802
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0