version: '2'
services:
  che:
    image: eclipse/che
    ports:
      - '5802:80'
    environment:
      - CHE_PORT:5802
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/opt/volumn/che:/data'
