version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "5804:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "5805:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "5807:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: welcome1
      KM_ARGS: -Djava.net.preferIPv4Stack=true
